name: Deploy docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SciCatProject/scicatlive/.github/actions/mkdocs-pages@clean_false
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          push: true
