name: Deploy docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get directory
        run: ls -a
      - name: Copy all to docs folder
        shell: bash
        run: |
          mkdir -p docs
          shopt -s extglob
          mv !(docs) docs/
      - uses: SciCatProject/scicatlive/.github/actions/mkdocs-pages@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          push: true
